Repository World-Meteorological-Organization/wis2box, pull requests merged in 2022-10, with the labels that each got.

#272 add data-id to notification message (#268)
  wis2box/data/base.py
  wis2box/pubsub/message.py
Labels: bug

#273 add client id to pubsub broker client
  wis2box/data/base.py
  wis2box/plugin.py
  wis2box/pubsub/mqtt.py
  wis2box/pubsub/subscribe.py
Labels: enhancement

#274 add disconnect logging to MQTT broker
  wis2box/pubsub/mqtt.py
Labels: enhancement

#281 normalize on normalize on wigos_station_identifier (#280)
  docs/source/data-access/r-api.ipynb
  docs/source/extending-wis2box.rst
  tests/integration/test_workflow.py
  wis2box/data/bufr4.py
  wis2box/metadata/station.py
Labels: enhancement

#284 add wigos_station_identifier to data notifications
  Dockerfile
  tests/integration/test_workflow.py
  wis2box/data/base.py
  wis2box/pubsub/message.py
Labels: enhancement

#275 add username to cron.d (#240)
  Dockerfile
  docker/entrypoint.sh
  docker/wis2box/wis2box.cron
Labels: bug

#286 add memory limits for default ES setup
  docker/docker-compose.yml
Labels: api

#293 Pubsub message update
  docker/watchpuppy/watchpuppy.py
  wis2box/api/backend/elastic.py
  wis2box/pubsub/message.py
Labels: bug

#291 reduce ES indexes to one index per dataset, publish metadata to broker
  .github/workflows/tests-docker.yml
  docker/default.env
  docs/source/running/discovery-metadata.rst
  examples/config/surface-weather-observations.yml
  requirements.txt
  tests/data/metadata/discovery/dza-surface-weather-observations.yml
  tests/data/metadata/discovery/ita-surface-weather-observations.yml
  tests/data/metadata/discovery/mwi-surface-weather-observations.yml
  tests/integration/test_workflow.py
  wis2box/api/backend/elastic.py
  wis2box/api/config/pygeoapi.py
  wis2box/data/base.py
  wis2box/metadata/discovery.py
  wis2box/pubsub/mqtt.py
  wis2box/util.py
Labels: bug, enhancement, discovery metadata, api, data access

#308 Performance enhancements
  docker/docker-compose.monitoring.yml
  wis2box/pubsub/subscribe.py
Labels: performance

#312 add WSI as link relation to data notifications
  wis2box/pubsub/message.py
Labels: enhancement
