Repository World-Meteorological-Organization/wis2box, pull requests merged in 2023-11, with the labels that each got.

#564 updated docs for SSL
  docs/source/user/public-services-setup.rst
Labels: documentation

#569 fix Shapely requirement
  wis2box-management/Dockerfile
Labels: bug

#568 provide data inline to WNM
  docs/source/reference/quickstart.rst
  tests/integration/test_workflow.py
  wis2box-management/wis2box/pubsub/message.py
Labels: enhancement

#580 updates WCMP2 docs, examples and pywis-topics
  config-templates/metadata-synop.yml.tmpl
  config-templates/metadata-temp.yml.tmpl
  docs/source/user/setup.rst
  examples/config/surface-weather-observations.yml
  tests/data/metadata/discovery/cog-surface-weather-observations.yml
  tests/data/metadata/discovery/dza-surface-weather-observations.yml
  tests/data/metadata/discovery/ita-surface-weather-observations.yml
  tests/data/metadata/discovery/mwi-surface-weather-observations.yml
  tests/data/metadata/discovery/rou-synoptic-weather-observations.yml
  wis2box-management/Dockerfile
  wis2box-management/docker/entrypoint.sh
  wis2box-management/requirements.txt
  wis2box-management/wis2box/topic_hierarchy.py
Labels: discovery metadata

#570 merge country and centre-id
  .github/workflows/tests-docker.yml
  config-templates/data-mappings.yml.tmpl
  config-templates/metadata-synop.yml.tmpl
  config-templates/metadata-temp.yml.tmpl
  docs/source/_static/minio-new-folder-path.png
  docs/source/_static/minio-upload-files.png
  docs/source/_static/winscp_wis2box-ftp_example.png
  docs/source/reference/auth.rst
  docs/source/reference/data-access/python-api-owslib.ipynb
  docs/source/reference/data-access/python-api-requests.ipynb
  docs/source/reference/data-access/r-api.ipynb
  docs/source/reference/quickstart.rst
  docs/source/reference/services.rst
  docs/source/reference/storage.rst
  docs/source/user/data-ingest.rst
  docs/source/user/setup.rst
  examples/config/surface-weather-observations.yml
  examples/config/synop-bin-mappings.yml
  examples/config/synop-bufr-mappings.yml
  examples/config/synop-csv-mappings.yml
  examples/config/synop-synop-mappings.yml
  tests/data/data-mappings.yml
  tests/data/metadata/discovery/cd-surface-weather-observations.yml
  tests/data/metadata/discovery/dz-surface-weather-observations.yml
  tests/data/metadata/discovery/it-surface-weather-observations.yml
  tests/data/metadata/discovery/mw-surface-weather-observations.yml
  tests/data/metadata/discovery/ro-synoptic-weather-observations.yml
  tests/integration/test_workflow.py
  wis2box-create-config.py
  wis2box-management/wis2box/metadata/discovery.py
Labels: enhancement, topic-hierarchy
