Repository World-Meteorological-Organization/wis2box, pull requests merged in 2023-01, with the labels that each got.

#357 update to latest csv2bufr changes
  wis2box/data/base.py
  wis2box/data/csv2bufr.py
Labels: data transformation

#359 update example station list (#358)
  examples/config/station_list.csv
Labels: bug, documentation

#364 fix to display errors wis2box-management container
  grafana/dashboards/home.json
Labels: bug

#367 remove use of csv2bufr-templates
  examples/config/synop-csv-mappings.yml
  wis2box-management/docker/entrypoint.sh
  wis2box-management/wis2box/data/csv2bufr.py
  wis2box-management/wis2box/metadata/station.py
  wis2box-management/wis2box/resources/data-mappings.yml
Labels: bug

#368 update documentation for station_list.csv
  docs/source/community/troubleshooting.rst
  docs/source/reference/running/station-metadata.rst
  docs/source/user/setup.rst
Labels: documentation

#372 pin minio release image: 2022-12-02T19-19-22Z.fips
  docker-compose.yml
Labels: bug

#373 flush station API backend before re-publishing (#371)
  wis2box-management/wis2box/api/__init__.py
  wis2box-management/wis2box/api/backend/elastic.py
  wis2box-management/wis2box/metadata/station.py
Labels: bug

#374 check for WSI in csv2bufr and synop2bufr pipelines
  tests/data/observations/malawi/WIGOS_0-454-2-AWSTOLEZA_2021-11-18T0955.csv
  wis2box-management/wis2box/data/csv2bufr.py
  wis2box-management/wis2box/data/synop2bufr.py
Labels: bug, station metadata

#375 pin csv2bufr to 0.4.1
  wis2box-management/Dockerfile
Labels: data transformation

#380 add bufr4 plugin description (#313)
  docs/source/reference/running/data-pipeline-plugins.rst
  wis2box-management/wis2box/metadata/discovery.py
Labels: documentation

#385 Update example discovery metadata configuration
  examples/README.md
  examples/config/surface-weather-observations.yml
Labels: bug, discovery metadata
