Repository World-Meteorological-Organization/wis2box, pull requests merged in 2024-08, with the labels that each got.

#724 Update downloading-data.rst
  docs/source/user/downloading-data.rst
Labels: documentation

#733 improved monitoring stack
  docker-compose.monitoring.yml
  loki/loki-config.yml
Labels: monitoring

#723 add option to publish specific stations to a certain topic (#720)
  .github/workflows/tests-docker.yml
  docs/source/community/troubleshooting.rst
  docs/source/reference/quickstart.rst
  docs/source/reference/running/api-publishing.rst
  docs/source/reference/running/station-metadata.rst
  docs/source/user/setup.rst
  tests/data/metadata/station/algeria.csv
  tests/data/metadata/station/congo.csv
  tests/data/metadata/station/italy.csv
  tests/data/metadata/station/malawi.csv
  tests/data/metadata/station/romania.csv
  tests/data/metadata/station/wmo-test-buoy.csv
  tests/data/metadata/station/wmo-test-ship.csv
  tests/data/metadata/station/wmo-test-wind_profiler.csv
  wis2box-management/wis2box/env.py
  wis2box-management/wis2box/metadata/station.py
Labels: station metadata

#737 metadata for data-centric api
  wis2box-management/wis2box/data/bufr4.py
  wis2box-management/wis2box/data/csv2bufr.py
  wis2box-management/wis2box/data/synop2bufr.py
Labels: enhancement, discovery metadata

#739 add security property to WNM for access controlled data (#643)
  .github/workflows/tests-docker.yml
  docs/source/reference/quickstart.rst
  docs/source/user/data-ingest.rst
  tests/data/metadata/discovery/cd-surface-weather-observations.yml
  tests/integration/test_workflow.py
  wis2box-management/wis2box/auth.py
  wis2box-management/wis2box/metadata/discovery.py
  wis2box-management/wis2box/pubsub/message.py
Labels: access control

#741 check WCMP2 compliance with pywcmp, update to valid centre-ids
  .github/workflows/tests-docker.yml
  docs/source/reference/auth.rst
  docs/source/reference/data-access/python-api-owslib.ipynb
  docs/source/reference/data-access/python-api-requests.ipynb
  docs/source/reference/data-access/r-api.ipynb
  docs/source/reference/quickstart.rst
  docs/source/reference/services.rst
  docs/source/reference/storage.rst
  docs/source/user/data-ingest.rst
  docs/source/user/setup.rst
  tests/data/metadata/discovery/cd-surface-weather-observations.yml
  tests/data/metadata/discovery/dz-surface-weather-observations.yml
  tests/data/metadata/discovery/int-wmo-test-drifting-buoys.yml
  tests/data/metadata/discovery/int-wmo-test-ship-hourly.yml
  tests/data/metadata/discovery/int-wmo-test-wind-profile.yml
  tests/data/metadata/discovery/it-surface-weather-observations.yml
  tests/data/metadata/discovery/mw-surface-weather-observations.yml
  tests/data/metadata/discovery/ro-synoptic-weather-observations.yml
  tests/data/metadata/station/wmo-test-drifting-buoys.csv
  tests/data/metadata/station/wmo-test-ship-hourly.csv
  tests/data/metadata/station/wmo-test-wind-profile.csv
  tests/data/observations/wmo/drifting-buoys/A_IOBH03LFPW161000_C_EDZW_20240216112202_27622614.bin
  tests/data/observations/wmo/ship-hourly/A_ISSA05LFPW111700RRA_C_EDZW_20240211170705_50982396.bin
  tests/data/observations/wmo/wind-profile/WIGOS_0-20000-0-48698_20240301T140000-578.bin
  tests/integration/test_workflow.py
  tests/requirements.txt
Labels: discovery metadata

#756 to deal with first label in metric
  wis2box-mqtt-metrics-collector/mqtt_metrics_collector.py
Labels: bug

#753 update CI to checkout v4, fix docs build warnings
  .github/workflows/containers.yml
  .github/workflows/docs.yml
  .github/workflows/tests-docker.yml
  .github/workflows/zaproxy.yml
  docker-compose.monitoring.yml
  docker-compose.yml
  docs/Makefile
  docs/requirements.txt
  docs/source/user/gts-headers-in-wis2.rst
Labels: documentation
