Repository World-Meteorological-Organization/wis2box, pull requests merged in 2024-10, with the labels that each got.

#784 fix doc typo (#780)
  docs/source/user/data-ingest.rst
Labels: bug, documentation

#788 update GRIB/BUFR media types
  tests/integration/test_workflow.py
  wis2box-management/wis2box/pubsub/message.py
Labels: enhancement

#795 protect against empty data-mappings
  wis2box-management/wis2box/data_mappings.py
Labels: bug

#794 update for Ubuntu 24.0.4 as per feedback from WIS2 Training Brasilia channel
  docs/source/user/getting-started.rst
Labels: documentation
