Repository World-Meteorological-Organization/wis2box, pull requests merged in 2024-12, with the labels that each got.

#820 container config updates
  docker-compose.yml
Labels: security

#811 reorganizing the data-collection for new bufr2geojson oaproc output
  .zap/rules.tsv
  docker-compose.yml
  tests/integration/test_workflow.py
  wis2box-management/wis2box/api/__init__.py
  wis2box-management/wis2box/api/backend/elastic.py
  wis2box-management/wis2box/data/__init__.py
  wis2box-management/wis2box/data/bufr2geojson.py
  wis2box-management/wis2box/data/geojson.py
  wis2box-management/wis2box/data_mappings.py
  wis2box-management/wis2box/metadata/discovery.py
Labels: data management

#812 remove security handling in WCMP2 links
  tests/integration/test_workflow.py
  wis2box-management/wis2box/auth.py
Labels: bug, discovery metadata, security

#824 Include additional UI variables in docs
  docs/source/reference/configuration.rst
  wis2box-create-config.py
Labels: web application
