Repository World-Meteorological-Organization/wis2box, pull requests merged in 2025-01, with the labels that each got.

#828 Docs update
  docs/source/_static/wis2box-ui-datasets.png
  docs/source/reference/configuration.rst
  docs/source/user/public-services-setup.rst
Labels: documentation

#830 remove pywis-topics (unused) (#813)
  wis2box-management/Dockerfile
  wis2box-management/docker/entrypoint.sh
  wis2box-management/requirements.txt
Labels: discovery metadata, topic-hierarchy

#832 docs for adding users
  docs/source/user/public-services-setup.rst
Labels: documentation

#831 set CAP signature check based on env variable
  docs/source/reference/running/data-pipeline-plugins.rst
  wis2box-management/wis2box/data/cap_message.py
  wis2box-management/wis2box/util.py
Labels: data management

#837 add scheduler to trivy action (#836)
  .github/workflows/trivy.yml
Labels: security

#839 add/update csv2bufr plugin documentation
  docs/source/reference/running/data-pipeline-plugins.rst
  docs/source/user/data-ingest.rst
Labels: documentation

#844 use docker-compose-images file from separate repo to define images
  .gitignore
  .zap/rules.tsv
  VERSION.txt
  docker-compose.monitoring.yml
  docker-compose.yml
  docs/source/user/getting-started.rst
  wis2box-ctl.py
Labels: enhancement

#855 fix image link
  docs/source/reference/running/data-pipeline-plugins.rst
Labels: bug, documentation

#857 add support for building image from source code into wis2box-ctl.py ...
  wis2box-ctl.py
Labels: bug
