Repository World-Meteorological-Organization/wis2box, pull requests merged in 2025-02, with the labels that each got.

#862 safeguard auth paths
  .github/workflows/zaproxy.yml
  wis2box-management/wis2box/auth.py
Labels: bug, access control

#863 Mention image-file creation
  docs/source/user/setup.rst
Labels: documentation

#865 suppress WCMP2 language property
  wis2box-management/wis2box/metadata/discovery.py
Labels: discovery metadata

#867 update docs landing page
  docs/source/index.rst
  docs/source/user/introduction.rst
Labels: documentation
